server:
  port: 6002
spring:
  application:
    name: eureka-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://jhon:123456@localhost:8004/eureka/